apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: talent-consulting
  description: Talent Consulting
  links:
    - url: https://www.talentconsulting.uk/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: Talent Consulting
    email: info@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Maggie&flip=true&backgroundColor=ffdfbf
  children: [infrastructure]
